ALTER TABLE packets
    ADD COLUMN approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';

ALTER TABLE cases
    ADD COLUMN approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';

ALTER TABLE documents
    ADD COLUMN approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
